In [1]:
import os
import sys
import warnings
import pandas as pd

warnings.filterwarnings('ignore')

sys.path.append(os.path.join(os.getcwd(), 'workflow/lib'))
import ampseeker as amp

In [2]:
dataset = "nomads16"
wkdir = "../.."

In [3]:
# Parameters
dataset = "ag-vampir-combined"
platform = "illumina"
wkdir = "/mnt/user_shares/snagi/lstm_scratch/network_scratch/ampseq-agvampir-combined"

# SNP data

In this notebook, we display the variant calling and annotation results as a pandas dataframe and save it as an excel spreadsheet for the user to explore or analyse further. If the DataFrame is too large to display, please use the .xlsx file. 

#### Target SNP data

In [4]:
vcf_df = amp.vcf_to_excel(
    vcf_path=f"{wkdir}/results/vcfs/targets/{dataset}.annot.vcf",
    excel_path=f"{wkdir}/results/vcfs/targets/{dataset}-snps.xlsx",
    convert_genotypes=True,
    split_multiallelic=True,
)
pd.set_option("display.max_rows", 1000, "display.max_columns", 1000)
vcf_df

    CHROM       POS  FILTER_PASS REF ALT  \
0      2R   3492074        False   G   A
1      2R   8368731        False   A   C
2      2R  17854287        False   C   A
3      2R  28492879        False   A   G
4      2R  28494247        False   C   T
5      2R  28497563        False   T   C
6      2R  28497967        False   G   C
7      2R  28497967        False   G   A
8      2R  28499661        False   G   T
9      2R  28500643        False   G   A
10     2R  28501399        False   G   A
11     2R  28501399        False   G   T
12     2R  28502736        False   C   A
13     2R  28502850        False   C   T
14     2R  49438586        False   T   C
15     3R     34264        False   A   G
16     3R     35121        False   A   G
17     3R     38161        False   A   G
18     3R     42848        False   A   C
19     3R     50590        False   T   G
20     3R     71973        False   C   A
21     3R     71973        False   C   G
22     3R     97617        False   G   A
23     3R   8564156        False   G   A
24     3R  28592158        False   G   A
25     3R  28595449        False   C   T
26     3R  28598057        False   G   A
27     3R  28598057        False   G   C
28     3R  28598062        False   G   C
29     3R  28598166        False   A   G
30     3R  28600701        False   A   G
31     2L    209536        False   G   A
32     2L    209536        False   G   C
33     2L    927247        False   A   C
34     2L   1274353        False   A   G
35     2L   1274353        False   A  AG
36     2L   1418210        False   C   T
37     2L   1571929        False   C   T
38     2L   1776348        False   C   G
39     2L   1947574        False   A   G
40     2L   2380982        False   T   C
41     2L   2391228        False   G   T
42     2L   2399997        False   G   A
43     2L   2403941        False   T   A
44     2L   2403941        False   T   C
45     2L   2414062        False   A   G
46     2L   2416980        False   C   T
47     2L   2422651        False   T   C
48     2L   2422652        False   A   T
49     2L   2425052        False   G   A
50     2L   2425766        False   T   C
51     2L   2429617        False   T   C
52     2L   2429745        False   A   T
53     2L   2429897        False   A   G
54     2L   2430424        False   G   T
55     2L   2430817        False   G   A
56     2L   2430817        False   G   C
57     2L   2430863        False   T   C
58     2L   2430880        False   C   T
59     2L   2430881        False   C   T
60     2L   2431005        False   C   T
61     2L   2432419        False   T   G
62     2L   2435581        False   G   A
63     2L  20288132        False   T   C
64     2L  25429235        False   G   T
65     2L  25429236        False   C   G
66     2L  25429236        False   C   T
67     2L  25635973        False   G   A
68     2L  34100758        False   A   T
69     2L  34100758        False   A   G
70     2L  34118141        False   G   A
71     2L  34118260        False   G   A
72     2L  34118260        False   G   T
73     3L     65133        False   G   T
74     3L    129051        False   A   C
75     3L    193173        False   A   G
76     3L    367248        False   C   A
77     3L    367248        False   C   G
78     3L    380974        False   C   A
79     3L    413508        False   A   G
80     3L  11208465        False   A   T
81     3L  11208465        False   A   G
82     3L  11213955        False   G   T
83     3L  11213955        False   G   A
84      X  15251490        False   C   T
85      X  15255321        False   A   T
86      X  18758300        False   C   T
87      X  19631625        False   C   G
88      X  20014696        False   A   C
89      X  20014696        False   A   T
90      X  20014696        False   A   G
91      X  20128328        False   C   T
92      X  20129288        False   G   T
93      X  21721801        False   C   G
94      X  22164043        False   C   T
95      X  22798648        False   A   C
96      X  22798648        False   A   T
97      X  23468268        False   A   T
98      X  23468268        False   A   C
99      X  24229846        False   A   G
100     X  24266728        False   A   T

                                                   ANN GH_01 GH_02 GH_03  \
0    A|missense_variant|MODERATE|ACE1|AGAP001356|tr...     2     2   NaN
1    C|synonymous_variant|LOW|AGAP001684|AGAP001684...     2     2   NaN
2    A|synonymous_variant|LOW|GPR5HT2A|AGAP002232|t...     2     2   NaN
3    G|missense_variant|MODERATE|CYP6P3|AGAP002865|...     0     0   NaN
4    T|missense_variant|MODERATE|CYP6P5|AGAP002866|...     0     0   NaN
5    C|splice_region_variant&intron_variant|LOW|CYP...     0     0   NaN
6    C|missense_variant|MODERATE|CYP6P4|AGAP002867|...     0     0   NaN
7    C|missense_variant|MODERATE|CYP6P4|AGAP002867|...     0     0   NaN
8    T|missense_variant|MODERATE|CYP6P1|AGAP002868|...     0     0     0
9    A|missense_variant|MODERATE|CYP6P1|AGAP002868|...     0     0   NaN
10   A|missense_variant|MODERATE|CYP6P2|AGAP002869|...     0     0   NaN
11   A|missense_variant|MODERATE|CYP6P2|AGAP002869|...     0     0   NaN
12   A|missense_variant|MODERATE|CYP6P2|AGAP002869|...     0     0   NaN
13   T|synonymous_variant|LOW|CYP6P2|AGAP002869|tra...     0     0   NaN
14   C|3_prime_UTR_variant|MODIFIER|AGAP013121|AGAP...     0     0   NaN
15   G|intron_variant|MODIFIER|AGAP007732|AGAP00773...     2     2     0
16   G|intron_variant|MODIFIER|AGAP007732|AGAP00773...     2     2     0
17   G|intron_variant|MODIFIER|AGAP007732|AGAP00773...     2     2     0
18   C|intergenic_region|MODIFIER|AGAP007733-AGAP00...     2     2     0
19   G|intergenic_region|MODIFIER|AGAP007733-AGAP00...     2     2   NaN
20   A|intergenic_region|MODIFIER|AGAP007734-AGAP00...     2     2     0
21   A|intergenic_region|MODIFIER|AGAP007734-AGAP00...     0     0     0
22   A|intron_variant|MODIFIER|AGAP007736|AGAP00773...     2     2   NaN
23   A|intergenic_region|MODIFIER|D7r1-AGAP008285|A...     0     0   NaN
24   A|synonymous_variant|LOW|GSTE8|AGAP009190|tran...   NaN   NaN   NaN
25   T|missense_variant|MODERATE|GSTE5|AGAP009192|t...     0     1   NaN
26   C|missense_variant|MODERATE|GSTE2|AGAP009194|t...     0     0   NaN
27   C|missense_variant|MODERATE|GSTE2|AGAP009194|t...     0     0   NaN
28   C|missense_variant|MODERATE|GSTE2|AGAP009194|t...     1     2   NaN
29   G|missense_variant|MODERATE|GSTE2|AGAP009194|t...     0     0     1
30   G|intron_variant|MODIFIER|GSTE7|AGAP009196|tra...     1     0     0
31   A|missense_variant|MODERATE|AGAP004679|AGAP004...     2     2   NaN
32   A|missense_variant|MODERATE|AGAP004679|AGAP004...     0     0   NaN
33   C|intergenic_region|MODIFIER|AGAP004687-AGAP02...     2     2   NaN
34   G|intron_variant|MODIFIER|AGAP004691|AGAP00469...     2     2     2
35   AG|intron_variant|MODIFIER|AGAP004691|AGAP0046...   NaN   NaN   NaN
36   T|intron_variant|MODIFIER|AGAP004692|AGAP00469...     2     2   NaN
37   T|intergenic_region|MODIFIER|AGAP004693-AGAP00...     2     2   NaN
38   G|missense_variant|MODERATE|AGAP029368|AGAP029...     2     2   NaN
39   G|intron_variant|MODIFIER|exd|AGAP004696|trans...     2     2   NaN
40   C|intron_variant|MODIFIER|para|AGAP004707|tran...     0     0   NaN
41   T|missense_variant|MODERATE|para|AGAP004707|tr...     0     0   NaN
42   A|missense_variant|MODERATE|para|AGAP004707|tr...     0   NaN   NaN
43   A|intron_variant|MODIFIER|para|AGAP004707|tran...     0     0   NaN
44   A|intron_variant|MODIFIER|para|AGAP004707|tran...     0     0   NaN
45   G|intron_variant|MODIFIER|para|AGAP004707|tran...     0   NaN   NaN
46   T|missense_variant|MODERATE|para|AGAP004707|tr...     1     2   NaN
47   C|missense_variant|MODERATE|para|AGAP004707|tr...     0     0   NaN
48   T|missense_variant|MODERATE|para|AGAP004707|tr...     2     2   NaN
49   A|synonymous_variant|LOW|para|AGAP004707|trans...     0     0   NaN
50   C|splice_region_variant&intron_variant|LOW|par...     0     0     0
51   C|missense_variant|MODERATE|para|AGAP004707|tr...     0     0     0
52   T|missense_variant|MODERATE|para|AGAP004707|tr...     0     0   NaN
53   G|missense_variant|MODERATE|para|AGAP004707|tr...     0     0   NaN
54   T|missense_variant|MODERATE|para|AGAP004707|tr...     1     2   NaN
55   A|missense_variant|MODERATE|para|AGAP004707|tr...     0     0     0
56   A|missense_variant|MODERATE|para|AGAP004707|tr...     0     0     0
57   C|missense_variant|MODERATE|para|AGAP004707|tr...     0     0   NaN
58   T|missense_variant|MODERATE|para|AGAP004707|tr...     0     0   NaN
59   T|missense_variant|MODERATE|para|AGAP004707|tr...     1     0   NaN
60   T|synonymous_variant|LOW|para|AGAP004707|trans...     2     2   NaN
61   G|intergenic_region|MODIFIER|para-AGAP004708|A...     0     0   NaN
62   A|intergenic_region|MODIFIER|para-AGAP004708|A...     2     2     1
63   C|synonymous_variant|LOW|COEAE1D|AGAP005756|tr...   NaN   NaN     0
64   T|missense_variant|MODERATE|Rdl|AGAP006028|tra...     0     0   NaN
65   G|missense_variant|MODERATE|Rdl|AGAP006028|tra...     1     2   NaN
66   G|missense_variant|MODERATE|Rdl|AGAP006028|tra...     0     0   NaN
67   A|missense_variant|MODERATE|CYP4J5|AGAP006048|...     0     0     0
68   G|5_prime_UTR_premature_start_codon_gain_varia...     0     0   NaN
69   G|5_prime_UTR_premature_start_codon_gain_varia...     0     0   NaN
70   A|missense_variant|MODERATE|AGAP006551|AGAP006...     0     0   NaN
71   A|intergenic_region|MODIFIER|AGAP006551-AGAP00...     0     0   NaN
72   A|intergenic_region|MODIFIER|AGAP006551-AGAP00...     0     0   NaN
73   T|intergenic_region|MODIFIER|CHR_START-AGAP010...   NaN   NaN   NaN
74   C|intron_variant|MODIFIER|AGAP010311|AGAP01031...     2     2   NaN
75   G|intron_variant|MODIFIER|AGAP010312|AGAP01031...     0     0   NaN
76   A|intron_variant|MODIFIER|AGAP010314|AGAP01031...     0     0     0
77   A|intron_variant|MODIFIER|AGAP010314|AGAP01031...     0     0     0
78   A|intron_variant|MODIFIER|AGAP029563|AGAP02956...     0     0   NaN
79   G|missense_variant|MODERATE|AGAP010317|AGAP010...     2   NaN   NaN
80   G|intergenic_region|MODIFIER|TEP1-TEP3|AGAP010...     0     0   NaN
81   G|intergenic_region|MODIFIER|TEP1-TEP3|AGAP010...     0     0   NaN
82   A|intergenic_region|MODIFIER|TEP1-TEP3|AGAP010...     0     0     0
83   A|intergenic_region|MODIFIER|TEP1-TEP3|AGAP010...     0     0     0
84   T|intergenic_region|MODIFIER|CYP9K1-AGAP000819...     0     0   NaN
85   T|intergenic_region|MODIFIER|AGAP000819-CPR125...     0     0   NaN
86   T|intron_variant|MODIFIER|AGAP000974|AGAP00097...     2     2     2
87   G|intron_variant|MODIFIER|GPRCCK1|AGAP001022|t...     2     2   NaN
88   C|intron_variant|MODIFIER|CYP307A1|AGAP001039|...     2     2   NaN
89   C|intron_variant|MODIFIER|CYP307A1|AGAP001039|...     0     0   NaN
90   C|intron_variant|MODIFIER|CYP307A1|AGAP001039|...     0     0   NaN
91   T|intron_variant|MODIFIER|arm|AGAP001043|trans...     2     2   NaN
92   T|intron_variant|MODIFIER|arm|AGAP001043|trans...     2     2   NaN
93   G|intergenic_region|MODIFIER|AGAP013021-AGAP00...     2     2   NaN
94   T|intron_variant|MODIFIER|AGAP001061|AGAP00106...     2   NaN   NaN
95   C|intron_variant|MODIFIER|AGAP001073|AGAP00107...     2     2     2
96   C|intron_variant|MODIFIER|AGAP001073|AGAP00107...     0     0     0
97   C|missense_variant|MODERATE|AGAP001082|AGAP001...     2     2   NaN
98   C|missense_variant|MODERATE|AGAP001082|AGAP001...     0     0   NaN
99   G|intergenic_region|MODIFIER|AGAP001093-run|AG...     2   NaN     0
100  T|intergenic_region|MODIFIER|run-SSU_rRNA_euka...     2     2   NaN

    GH_04 GH_05 GH_06 GH_07 GH_08 GH_09 GH_10 GH_11 GH_12 GH_13 GH_14 GH_15  \
0       2     2     2     2   NaN   NaN     2     2     2     2     1     2
1       2     2     2     2   NaN   NaN     2     2     2     2     2     2
2       2     2     2   NaN   NaN   NaN     2     2     2     2     2     2
3       0     0     0     0   NaN   NaN     0     0     0     0     0     0
4     NaN   NaN     0   NaN   NaN   NaN     0     0   NaN     0     0   NaN
5       0     0     0   NaN   NaN   NaN     0     0     0     0     0     0
6       0     0     0     0   NaN     0     0     0   NaN     0     0     0
7       0     0     0     0   NaN     0     0     0   NaN     0     0     0
8     NaN     1     1     1     0     0     1     1     0     2     2     2
9       0     0     0   NaN   NaN   NaN     0     0   NaN     0     0     0
10    NaN   NaN     0   NaN   NaN   NaN     0   NaN   NaN     0     0     0
11    NaN   NaN     0   NaN   NaN   NaN     0   NaN   NaN     0     0     0
12    NaN     0     0   NaN     0   NaN     0   NaN     0     0     0     0
13    NaN     1     0   NaN   NaN   NaN     2   NaN     0     0     0     0
14      0     0     0   NaN   NaN   NaN     0     0     0     0     0     0
15      2     2     2     0     0   NaN     2     2     2     2     2     2
16      2     2     2     2     0     0     2     1     2     2     2     2
17      2     2     2   NaN   NaN     0     2   NaN     1     2     2   NaN
18      2   NaN     2   NaN     0     0     2     1   NaN     2     2     2
19      2     2     2   NaN   NaN   NaN     2     2   NaN     2     2     2
20    NaN     2     2     2   NaN     0     2     2   NaN     2     2     2
21    NaN     0     0     0   NaN     0     0     0   NaN     0     0     0
22      2     0     2     2   NaN   NaN     2     1     2     2     2     2
23      0     1     0     0   NaN   NaN     0     0   NaN     1     0     0
24    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
25      0   NaN   NaN   NaN   NaN     0     0   NaN     0     0     2   NaN
26    NaN   NaN     0     0   NaN   NaN     0     0   NaN   NaN     0     0
27    NaN   NaN     0     0   NaN   NaN     0     0   NaN   NaN     0     0
28    NaN   NaN     2     2   NaN   NaN     0     0   NaN   NaN     0     2
29    NaN   NaN     0     0     0     0     0     0   NaN   NaN     0     0
30    NaN   NaN     0   NaN     0     0     0     0     0   NaN     0   NaN
31      2     2     2   NaN   NaN   NaN     2     2   NaN     2     2   NaN
32      0     0     0   NaN   NaN   NaN     0     0   NaN     0     0   NaN
33      2     2     2     2   NaN   NaN     2     2   NaN     2     2     2
34    NaN     2     2     2   NaN   NaN     2     2   NaN     2     2     2
35    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
36    NaN     2     2     2   NaN   NaN     2     2   NaN     2     2     2
37    NaN     2     2     2   NaN   NaN   NaN     2   NaN     2     2     2
38    NaN   NaN     2   NaN     2     2   NaN   NaN   NaN     2     2   NaN
39    NaN     2     2     2   NaN   NaN     2     2   NaN     2     2     2
40    NaN     0     0   NaN   NaN   NaN     0     0     0     0     0     0
41    NaN     0     0   NaN   NaN   NaN     0     0     0     0     0     0
42      0     0     0   NaN   NaN   NaN   NaN   NaN   NaN     0     0   NaN
43    NaN     0     0   NaN     0     0     0     0     0     0     0     0
44    NaN     0     0   NaN     0     0     0     0     0     0     0     0
45    NaN     0     0     0   NaN     0     0     0   NaN     0     0     0
46    NaN   NaN     1   NaN   NaN   NaN     2     0   NaN     1     0     1
47      0     0     0     0   NaN   NaN   NaN     0   NaN     0     0     0
48      2     2     2     2   NaN   NaN   NaN     2   NaN     2     2     2
49      0     0     0   NaN   NaN   NaN     0     0     0     0     0     0
50      0     0     0   NaN     0     0     0     0     0     0     0     0
51      0     0     0   NaN     0   NaN     0     0     0     0     0     0
52      0     0     1     0   NaN   NaN     0     0   NaN     0     1     0
53      0     0     0     0   NaN   NaN     0     0   NaN     0     0     0
54      1     1     1     1   NaN   NaN     2     0     2     1     0     1
55      0     0     0   NaN   NaN     0     0     0     0     1     1     0
56      0     0     0   NaN   NaN     0     0     0     0     0     0     0
57      0     0     0   NaN   NaN   NaN     0   NaN     0     0     0   NaN
58      0     0     0   NaN   NaN   NaN     0   NaN     0     0     0   NaN
59      2     1     0   NaN   NaN   NaN     0   NaN     0     0     0   NaN
60      2     2     2     2   NaN   NaN     2     2     2     2     2     2
61      0     0     0   NaN   NaN   NaN     0   NaN   NaN     0     0   NaN
62      2     2     2   NaN   NaN     2     2   NaN     2     2     2     2
63    NaN   NaN   NaN   NaN     0     0   NaN     0   NaN     2   NaN   NaN
64    NaN     0     0   NaN     1     0     0     0   NaN     0     0     0
65    NaN     2     1   NaN     0     0     2     0   NaN     1     1     2
66    NaN     0     0   NaN     0     0     0     0   NaN     0     0     0
67      0     0     1   NaN     1     0     0     1     0     0     1     0
68      0     0     0   NaN     0     2     0     0     0     0     0     0
69      0     0     0   NaN     0     0     0     0     0     0     0     0
70      0     0     0     0   NaN   NaN     0     0     0     0     0     0
71      0     0     0     0   NaN   NaN     0     0     0     0     0     0
72      0     0     0     0   NaN   NaN     0     0     0     0     0     0
73    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     2
74      1     2     2     2   NaN   NaN     2     2     2     2     2     2
75    NaN     0     0   NaN   NaN   NaN     0     0   NaN     0     0   NaN
76      0     0     0   NaN     2     2     0     2     0     1     0     0
77      0     0     0   NaN     0     0     0     0     0     0     0     0
78      0   NaN     0     0   NaN   NaN     0     0     0     0     0     0
79      2     2     2   NaN     0     0     2     2     0     2     2     2
80      0     0     0   NaN   NaN   NaN     0     0   NaN     0     0     0
81      0     0     0   NaN   NaN   NaN     0     0   NaN     0     0     0
82    NaN     0     0     0     0     0     0     0     0     0     0     0
83    NaN     0     0     0     0     0     0     0     0     0     0     0
84      0     0     0     0   NaN   NaN     0     0     0     0     0     0
85      0   NaN     0   NaN   NaN   NaN     0     0   NaN     0     0   NaN
86      2     2     2     2     0   NaN     2     2     2     2     2     2
87    NaN     2     2   NaN   NaN   NaN     2     2     2     2     2     2
88      2     2     2     2   NaN   NaN   NaN     2     2     2     2     2
89      0     0     0     0   NaN   NaN   NaN     0     0     0     0     0
90      0     0     0     0   NaN   NaN   NaN     0     0     0     0     0
91      2     2     2   NaN   NaN   NaN     2     2     2     2     2     2
92      2     2     2     2   NaN   NaN     2     2     2     2     2     2
93      2     2     2   NaN   NaN   NaN     2   NaN   NaN     2     2     2
94      2   NaN     2     2   NaN   NaN     2     2   NaN     2     2   NaN
95      2     2     2   NaN     2     2     2     2   NaN     2     2     2
96      0     0     0   NaN     0     0     0     0   NaN     0     0     0
97    NaN     2     2   NaN     0   NaN     2     2     2     2     2     2
98    NaN     0     0   NaN     0   NaN     0     0     0     0     0     0
99    NaN   NaN     2   NaN     0     0   NaN     0     0   NaN   NaN     2
100   NaN     2     2   NaN   NaN   NaN     2     2   NaN     2     2     2

    GH_16 GH_17 GH_18 GH_19 GH_20 GH_21 GH_22 GH_23 GH_24 GH_25 GH_26 GH_27  \
0       2     2     2     2   NaN     2     2     2   NaN     2     2     2
1     NaN     2     2     2   NaN     2     2   NaN   NaN     2     2     2
2       2     2   NaN     2     2     2     2   NaN   NaN     2     2     2
3       0     0     0     0     0     0     0   NaN   NaN     0     0     0
4       0     0     0     0   NaN     0     0   NaN   NaN     0     0     0
5       0     0     0     0     0     0     0     0   NaN     0     0     0

---

In [5]:
from IPython.display import display, Markdown
display(Markdown(f'<a href="{wkdir}/results/vcfs/targets/{dataset}-snps.xlsx">Target SNP data (.xlsx)</a>'))
display(Markdown(f'<a href="{wkdir}/results/vcfs/targets/{dataset}.annot.vcf">Target SNP data (.vcf)</a>'))

<a href="/mnt/user_shares/snagi/lstm_scratch/network_scratch/ampseq-agvampir-combined/results/vcfs/targets/ag-vampir-combined-snps.xlsx">Target SNP data (.xlsx)</a>

<a href="/mnt/user_shares/snagi/lstm_scratch/network_scratch/ampseq-agvampir-combined/results/vcfs/targets/ag-vampir-combined.annot.vcf">Target SNP data (.vcf)</a>

#### Whole-amplicon SNP data

For times sake, we do not write out whole-amplicon .xlsx by default - it is slow.

In [6]:
vcf_df = amp.vcf_to_excel(
    vcf_path=f"{wkdir}/results/vcfs/amplicons/{dataset}.annot.vcf",
    excel_path=f"{wkdir}/results/vcfs/amplicons/{dataset}-snps.xlsx",
    convert_genotypes=True,
    split_multiallelic=True
)
vcf_df

,CHROM,POS,FILTER_PASS,REF,ALT,ANN,GH_01,GH_02,GH_03,GH_04,GH_05,GH_06,GH_07,GH_08,GH_09,GH_10,GH_11,GH_12,GH_13,GH_14,GH_15,GH_16,GH_17,GH_18,GH_19,GH_20,GH_21,GH_22,GH_23,GH_24,GH_25,GH_26,GH_27,GH_28,GH_29,GH_30,GH_31,GH_32,GH_33,GH_34,GH_35,GH_36,GH_37,GH_38,GH_39,GH_40_low_vol,GH_41,GH_42,GH_43,GH_44,GH_45,GH_46,GH_47,GH_48,GH_49,GH_50,GH_51,GH_52,GH_53,GH_54,GH_55,GH_56,GH_57,GH_58,GH_59,GH_60,GH_61,GH_62,GH_63,GH_64,GH_65_low_vol,GH_66,GH_67,GH_68,GH_69,GH_70,GH_71,GH_72,GH_73,GH_74,GH_75,GH_76,GH_77,GH_78,GH_79,GH_80_low_vol,GH_81,GH_82,GH_83,GH_84,GH_85,GH_86,GH_87,GH_88,GH_89,GH_90,GH_91,GH_92,GH_93,GH_94,GH_95,GH_Negative,GM_01,GM_02,GM_03,GM_04,GM_05,GM_06,GM_07,GM_08,GM_09,GM_10,GM_11,GM_12,GM_13,GM_14,GM_15,GM_16,GM_17,GM_18,GM_19,GM_20,GM_21,GM_22,GM_23,GM_24,GM_25,GM_26,GM_27,GM_28,GM_29,GM_30,GM_31,GM_32,GM_33,GM_34,GM_35,GM_36,GM_37,GM_38,GM_39,GM_40,GM_41,GM_42,GM_43,GM_44,GM_45,GM_46,GM_47,GM_48,GM_49,GM_50,GM_51,GM_52,GM_53,GM_54,GM_55,GM_56,GM_57,GM_58,GM_59,GM_60,GM_61,GM_62,GM_63,GM_64,GM_65,GM_66,GM_67,GM_68,GM_69,GM_70,GM_71,GM_72,GM_73,GM_74,GM_75,GM_76,GM_77,GM_78,GM_79,GM_80,GM_81,GM_82,GM_83,GM_84,GM_85,GM_86,GM_87,GM_88,GM_89,GM_90,GM_91,GM_92,GM_93,GM_94,GM_95,GM_96,VK7_dead_01,VK7_dead_02,VK7_dead_03,VK7_dead_04,VK7_dead_05,VK7_dead_06,VK7_alive_01,VK7_alive_02,VK7_alive_03,VK7_alive_04,VK7_alive_05,VK7_alive_06,VK7_dead_07,VK7_dead_08,VK7_dead_09,VK7_dead_10,VK7_dead_11,VK7_dead_12,VK7_alive_07,VK7_alive_08,VK7_alive_09,VK7_alive_10,VK7_alive_11,VK7_alive_12,VK7_dead_13,VK7_dead_14,VK7_dead_15,VK7_dead_16,VK7_dead_17,VK7_dead_04_dil,VK7_alive_13,VK7_alive_14,VK7_alive_15,VK7_alive_16,VK7_alive_17,VK7_alive_18,VK7_dead_18,VK7_dead_19,VK7_dead_20,VK7_dead_21,VK7_dead_22,VK7_dead_10_dil,VK7_alive_19,VK7_alive_20,VK7_alive_21,VK7_alive_22,VK7_alive_23,VK7_alive_24,VK7_dead_23,VK7_dead_24,VK7_dead_25,VK7_dead_26,VK7_dead_27,VK7_dead_16_dil,VK7_alive_25,VK7_alive_26,VK7_alive_27,VK7_alive_28,VK7_alive_29,VK7_alive_30,VK7_dead_28,VK7_dead_29,VK7_dead_30,VK7_dead_31,VK7_dead_32,VK7_dead_22_dil,VK7_alive_31,VK7_alive_32,VK7_alive_33,VK7_alive_34,VK7_alive_35,VK7_alive_36,VK7_dead_33,VK7_dead_34,VK7_dead_35,VK7_dead_36,VK7_dead_37,VK7_dead_28_dil,VK7_alive_37,VK7_alive_38,VK7_alive_39,VK7_alive_40,VK7_alive_41,VK7_alive_42,VK7_dead_38,VK7_dead_39,VK7_dead_40,VK7_dead_41,VK7_dead_42,VK7_dead_34_dil,VK7_alive_43,VK7_alive_44,VK7_alive_45,VK7_alive_46,VK7_alive_47,VK7_Negative,Siaya_Delta_Dead_01,Siaya_Delta_Dead_02,Siaya_Delta_Dead_03,Siaya_Delta_Dead_04,Siaya_Delta_Dead_05,Siaya_Delta_Dead_06,Siaya_Delta_Dead_07,Siaya_Delta_Dead_08,Siaya_Delta_Dead_09,Siaya_Delta_Dead_10,Siaya_Delta_Dead_11,Siaya_Delta_Dead_12,Siaya_Delta_Dead_13,Siaya_Delta_Dead_14,Siaya_Delta_Dead_15,Siaya_Delta_Dead_16,Siaya_Delta_Dead_17,Siaya_Delta_Dead_18,Siaya_Delta_Dead_19,Siaya_Delta_Dead_20,Siaya_Delta_Dead_21,Siaya_Delta_Dead_22,Siaya_Delta_Dead_23,Siaya_Delta_Dead_24,Siaya_Delta_Dead_25,Siaya_Delta_Dead_26,Siaya_Delta_Dead_27,Siaya_Delta_Dead_28,Siaya_Delta_Dead_29,Siaya_Delta_Dead_30,Siaya_Delta_Dead_31,Siaya_Delta_Dead_32,Siaya_Delta_Dead_33,Siaya_Delta_Dead_34,Siaya_Delta_Dead_35,Siaya_Delta_Dead_36,Siaya_Delta_Dead_37,Siaya_Delta_Dead_38,Siaya_Delta_Dead_39,Siaya_Delta_Dead_40,Siaya_Delta_Dead_41,Siaya_Delta_Dead_42,Siaya_Delta_Dead_43,Siaya_Delta_Dead_44,Siaya_Delta_Dead_45,Siaya_Delta_Dead_46,Siaya_Delta_Dead_47,Siaya_Delta_Dead_48,Siaya_Delta_Dead_49,Siaya_Delta_Dead_50,Siaya_Delta_Dead_51,Siaya_Delta_Dead_52,Siaya_Delta_Dead_53,Siaya_Delta_Dead_54,Siaya_Delta_Dead_55,Siaya_Delta_Dead_56,Siaya_Delta_Dead_57,Siaya_Delta_Dead_58,Siaya_Delta_Dead_59,Siaya_Delta_Dead_60,Siaya_Delta_Dead_61,Siaya_Delta_Dead_62,Siaya_Delta_Dead_63,Siaya_Delta_Dead_64,Siaya_Delta_Dead_65,Siaya_Delta_Dead_66,Siaya_Delta_Dead_67,Siaya_Delta_Dead_68,Siaya_Delta_Dead_69,Siaya_Delta_Dead_70,Siaya_Delta_Dead_71,Siaya_Delta_Dead_72,Siaya_Delta_Dead_73,Siaya_Delta_Dead_74,Siaya_Delta_Dead_75,Siaya_Delta_Dead_76,Siaya_Delta_Dead_77,Siaya_Delta_Dead_78,Siaya_Delta_Dead_79,Siaya_Delta_Dead_80,Siaya_Delta_Dead_81,Siaya_Delta_Dead_82,Siaya_Delta_Dead_83,Siaya_Delta_Dead_84,Siaya_Delta_Dead_85,Siaya_Delta_Dead_86,Siaya_Delta_Dead_87,Siaya_Delta_Dead_88,Siaya_Delta_Dead_89,Siaya_Delta_Dead_90,Siaya_Delta_Dead_91,Siaya_Delta_Dead_92,Siaya_Delta_Dead_93,Siaya_Delta_Dead_94,Siaya_Delta_Dead_95,Siaya_Delta_Dead_Negative,Siaya_Delta_Alive_01,Siaya_Delta_Alive_02,Siaya_Delta_Alive_03,Siaya_Delta_Alive_04,Siaya_Delta_Alive_05,Siaya_Delta_Alive_06,Siaya_Delta_Alive_07,Siaya_Delta_Alive_08,Siaya_Delta_Alive_09,Siaya_Delta_Alive_10,Siaya_Delta_Alive_11,Siaya_Delta_Alive_12,Siaya_Delta_Alive_13,Siaya_Delta_Alive_14,Siaya_Delta_Alive_15,Siaya_Delta_Alive_16,Siaya_Delta_Alive_17,Siaya_Delta_Alive_18,Siaya_Delta_Alive_19,Siaya_Delta_Alive_20,Siaya_Delta_Alive_21,Siaya_Delta_Alive_22,Siaya_Delta_Alive_23,Siaya_Delta_Alive_24,Siaya_Delta_Alive_25,Siaya_Delta_Alive_26,Siaya_Delta_Alive_27,Siaya_Delta_Alive_28,Siaya_Delta_Alive_29,Siaya_Delta_Alive_30,Siaya_Delta_Alive_31,Siaya_Delta_Alive_32,Siaya_Delta_Alive_33,Siaya_Delta_Alive_34,Siaya_Delta_Alive_35,Siaya_Delta_Alive_36,Siaya_Delta_Alive_37,Siaya_Delta_Alive_38,Siaya_Delta_Alive_39,Siaya_Delta_Alive_40,Siaya_Delta_Alive_41,Siaya_Delta_Alive_42,Siaya_Delta_Alive_43,Siaya_Delta_Alive_44,Siaya_Delta_Alive_45,Siaya_Delta_Alive_46,Siaya_Delta_Alive_47,Siaya_Delta_Alive_48,Siaya_Delta_Alive_49,Siaya_Delta_Alive_50,Siaya_Delta_Alive_51,Siaya_Delta_Alive_52,Siaya_Delta_Alive_53,Siaya_Delta_Alive_54,Siaya_Delta_Alive_55,Siaya_Delta_Alive_56,Siaya_Delta_Alive_57,Siaya_Delta_Alive_58,Siaya_Delta_Alive_59,Siaya_Delta_Alive_60,Siaya_Delta_Alive_61,Siaya_Delta_Alive_62,Siaya_Delta_Alive_63,Siaya_Delta_Alive_64,Siaya_Delta_Alive_65,Siaya_Delta_Alive_66,Siaya_Delta_Alive_67,Siaya_Delta_Alive_68,Siaya_Delta_Alive_69,Siaya_Delta_Alive_70,Siaya_Delta_Alive_71,Siaya_Delta_Alive_72,Siaya_Delta_Alive_73,Siaya_Delta_Alive_74,Siaya_Delta_Alive_75,Siaya_Delta_Alive_76,Siaya_Delta_Alive_77,Siaya_Delta_Alive_78,Siaya_Delta_Alive_79,Siaya_Delta_Alive_80,Siaya_Delta_Alive_81,Siaya_Delta_Alive_82,Siaya_Delta_Alive_83,Siaya_Delta_Alive_84,Siaya_Delta_Alive_85,Siaya_Delta_Alive_86,Siaya_Delta_Alive_87,Siaya_Delta_Alive_88,Siaya_Delta_Alive_89,Siaya_Delta_Alive_90,Siaya_Delta_Alive_91,Siaya_Delta_Alive_92,Siaya_Delta_Alive_93,Siaya_Delta_Alive_94,Siaya_Delta_Alive_95,Siaya_Delta_Alive_Negative,Siaya_Delta_Dead_96,Siaya_Delta_Dead_97,Siaya_Delta_Dead_98,Siaya_Delta_Dead_99,Siaya_Delta_Dead_100,Siaya_Delta_Alive_96,Siaya_Delta_Alive_97,Siaya_Delta_Alive_98,Siaya_Delta_Alive_99,Siaya_Delta_Dead_101,Siaya_Delta_Dead_102,Siaya_Delta_Dead_103,Siaya_Delta_Dead_104,Siaya_Delta_Dead_105,Siaya_Delta_Alive_100,Siaya_Delta_Alive_101,Siaya_Delta_Alive_102,Siaya_Delta_Alive_103,Siaya_Delta_Dead_106,Siaya_Delta_Dead_107,Siaya_Delta_Dead_108,Siaya_Delta_Dead_109,Siaya_Delta_Dead_110,Siaya_Delta_Alive_104,Siaya_Delta_Alive_105,Siaya_Delta_Alive_106,Siaya_Delta_Alive_107,Siaya_Delta_Dead_111,Siaya_Delta_Dead_112,Siaya_Delta_Dead_113,Siaya_Delta_Dead_114,Siaya_Delta_Dead_115,Siaya_Delta_Alive_108,Siaya_Delta_Alive_109,Siaya_Delta_Alive_110,Siaya_Delta_Alive_111,Siaya_Delta_Dead_116,Siaya_Delta_Dead_117,Siaya_Delta_Dead_118,Siaya_Delta_Dead_119,Siaya_Delta_Alive_112,Siaya_Delta_Alive_113,Siaya_Delta_Alive_114,Siaya_Delta_Alive_115,Siaya_Delta_Alive_116,Siaya_Delta_Dead_120,Siaya_Delta_Dead_121,Siaya_Delta_Dead_122,Siaya_Delta_Dead_123,Siaya_Delta_Alive_117,Siaya_Delta_Alive_118,Siaya_Delta_Alive_119,Siaya_Delta_Alive_120,Siaya_Delta_Alive_121,Siaya_Delta_Dead_124,Siaya_Delta_Dead_125,Siaya_Delta_Dead_126,Siaya_Delta_Dead_127,Siaya_Delta_Alive_122,Siaya_Delta_Alive_123,Siaya_Delta_Alive_124,Siaya_Delta_Alive_125,Siaya_Delta_Alive_126,Siaya_Delta_Dead_128,Siaya_Delta_Dead_129,Siaya_Delta_Dead_130,Siaya_Delta_Dead_131,Siaya_Delta_Alive_127,Siaya_Delta_Alive_128,Siaya_Delta_Alive_129,Siaya_Delta_Alive_130,Siaya_Delta_Alive_131,G1,G9,G17,G25,G33,KIS_1,KIS_9,KIS_17,KIS_25,KIS_33,Tie_1,Tie_9,G2,G10,G18,G26,G34,KIS_2,KIS_10,KIS_18,KIS_26,KIS_34,Tie_2,Tie_10,G3,G11,G19,G27,G35,KIS_3,KIS_11,KIS_19,KIS_27,KIS_35,Tie_3,Tie_11,G4,G12,G20,G28,G36,KIS_4,KIS_12,KIS_20,KIS_28,KIS_36,Tie_4,Tie_12,G5,G13,G21,G29,G37,KIS_5,KIS_13,KIS_21,KIS_29,KIS_37,Tie_5,Tie_13,G6,G14,G22,G30,G38,KIS_6,KIS_14,KIS_22,KIS_30,KIS_38,Tie_6,Tie_14,G7,G15,G23,G31,G39,KIS_7,KIS_15,KIS_23,KIS_31,KIS_39,Tie_7,Tie_15,G8,G16,G24,G32,G40,KIS_8,KIS_16,KIS_24,KIS_32,KIS_40,Tie_8,NiC,Tie_16,Tie_24,Tie_32,Tie_40,Tia8,Tia16,Tia24,Tia32,Tia40,VK7_8,VK7_16,VK7_24,Tie_17,Tie_25,Tie_33,Tia1,Tia9,Tia17,Tia25,Tia33,VK7_1,VK7_9,VK7_17,VK7_25,Tie_18,Tie_26,Tie_34,Tia2,Tia10,Tia18,Tia26,Tia34,VK7_2,VK7_10,VK7_18,VK7_26,Tie_19,Tie_27,Tie_35,Tia3,Tia11,Tia19,Tia27,Tis35,VK7_3,VK7_11,VK7_19,VK7_27,Tie_20,Tie_28,Tie_36,Tia4,Tia12,Tia20,Tia28,Tia36,VK7_4,VK7_12,VK7_20,VK7_28,Tie_21,Tie_29,Tie_37,Tia5,Tia13,Tia21,Tia29,Tia37,VK7_5,VK7_13,VK7_21,VK7_29,Tie_22,Tie_30,Tie_38,Tia6,Tia14,Tia22,Tia30,Tia38,VK7_6,VK7_14,VK7_22,VK7_30,Tie_23,Tie_31,Tie_39,Tia7,Tia15,Tia23,Tia31,Tia39,VK7_7,VK7_15,VK7_23,Tie_41,KIS_43,KIS_51,VK7_34,VK7_42,Moz_8,Moz_16,Moz_24,Moz_32,Moz_40,NG_02,NG_10,KIS_44,KIS_52,VK7_35,Moz_1,Moz_9,Moz_17,Moz_25,Moz_33,Moz_41,NG_03,NG11,Tia_42,KIS_45,KIS_53,VK7_36,Moz_2,Moz_10,Moz_18,Moz_26,Moz_34,Moz_42,NG_04,NG_12,G41,KIS_46,KIS_54,VK7_37,Moz_3,Moz_11,Moz_19,Moz_27,Moz_35,Moz_43,NG_05,NG_13,G42,KIS_47,KIS_55,VK7_38,Moz_4,Moz_12,Moz_20,Moz_28,Moz_36,Moz_44,NG_06,NG_14,G43,KIS_48,VK7_31,VK7_39,Moz_5,Moz_13,Moz_21,Moz_29,Moz_37,Moz_45,NG_07,NG_15,KIS_41,KIS_49,VK7_32,VK7_40,Moz_6,Moz_14,Moz_22,Moz_30,Moz_38,Moz_46,NG_08,NG_16,KIS_42,KIS_50,VK7_33,VK7_41,Moz_7,Moz_15,Moz_23,Moz_31,Moz_39,NG_01,NG_09,NG17,NG25,NG33,NG41,SI_8,SI_16,SI_24,SI_32,SI_40,SI_48,SI_56,Tia_43,NG18,NG26,NG34,SI_1,SI_9,SI_17,SI_25,SI_33,SI_41,SI_49,SI_57,KIS_56,NG19,NG27,NG35,SI_2,SI_10,SI_18,SI_26,SI_34,SI_42,SI_50,SI_58,KIS_57,NG20,NG28,NG36,SI_3,SI_11,SI_19,SI_27,SI_35,SI_43,SI_51,SI_59,KIS_58,NG21,NG29,NG37,SI_4,SI_12,SI_20,SI_28,SI_36,SI_44,SI_52,SI_60,KIS_59,NG22,NG30,NG38,SI_5,SI_13,SI_21,SI_29,SI_37,SI_45,SI_53,SI_61,KIS_60,NG23,NG31,NG39,SI_6,SI_14,SI_22,SI_30,SI_38,SI_46,SI_54,SI_62,KIS_61,NG24,NG32,NG40,SI_7,SI_15,SI_23,SI_31,SI_39,SI_47,SI_55,Tie_42,Tia_66
0,2R,1621116,False,G,C,C|intergenic_region|MODIFIER|AGAP001218-TUB4A|...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2R,1621138,False,A,G,G|intergenic_region|MODIFIER|AGAP001218-TUB4A|...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

---

In [7]:
display(Markdown(f'<a href="{wkdir}/results/vcfs/amplicons/{dataset}-snps.xlsx">Whole amplicon SNP data (.xlsx)</a>'))
display(Markdown(f'<a href="{wkdir}/results/vcfs/amplicons/{dataset}.annot.vcf">Whole amplicon SNP data (.vcf)</a>'))

<a href="/mnt/user_shares/snagi/lstm_scratch/network_scratch/ampseq-agvampir-combined/results/vcfs/amplicons/ag-vampir-combined-snps.xlsx">Whole amplicon SNP data (.xlsx)</a>

<a href="/mnt/user_shares/snagi/lstm_scratch/network_scratch/ampseq-agvampir-combined/results/vcfs/amplicons/ag-vampir-combined.annot.vcf">Whole amplicon SNP data (.vcf)</a>